#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ALPS_T1_CNRM-CM5_static
python compute_scalars_cordex.py \
  --predictor-files /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/ESD_pseudo_reality/predictors/CNRM-CM5_1961-1980.nc \
  --target-files /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/ESD_pseudo_reality/target/pr_tasmax_CNRM-CM5_1961-1980.nc \
  --use-static \
  --orography-file /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/ESD_pseudo_reality/predictors/Static_fields.nc \
  --output-dir ./experiments/ALPS_T1_CNRM-CM5_static_scalars

python preproc_cordex.py \
  --predictor-files /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/ESD_pseudo_reality/predictors/CNRM-CM5_1961-1980.nc \
  --target-sample /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/ESD_pseudo_reality/target/pr_tasmax_CNRM-CM5_1961-1980.nc \
  --orography-file /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/ESD_pseudo_reality/predictors/Static_fields.nc \
  --output-dir /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/ESD_pseudo_reality/predictors \
  --input-vars u v q t z \
  --input-levels 850 700 500 \
  --regrid-method bilinear

# ALPS_T1_CNRM-CM5_no_static
python compute_scalars_cordex.py \
  --predictor-files /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/ESD_pseudo_reality/predictors/CNRM-CM5_1961-1980.nc \
  --target-files /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/ESD_pseudo_reality/target/pr_tasmax_CNRM-CM5_1961-1980.nc \
  --no-static \
  --output-dir ./experiments/ALPS_T1_CNRM-CM5_no_static_scalars

# ALPS_T2_CNRM-CM5_static
python compute_scalars_cordex.py \
  --predictor-files /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/Emulator_hist_future/predictors/CNRM-CM5_1961-1980_2080-2099.nc \
  --target-files /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/Emulator_hist_future/target/pr_tasmax_CNRM-CM5_1961-1980_2080-2099.nc \
  --use-static \
  --orography-file /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/Emulator_hist_future/predictors/Static_fields.nc \
  --output-dir ./experiments/ALPS_T2_CNRM-CM5_static_scalars

python preproc_cordex.py \
  --predictor-files /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/Emulator_hist_future/predictors/CNRM-CM5_1961-1980_2080-2099.nc \
  --target-sample /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/Emulator_hist_future/target/pr_tasmax_CNRM-CM5_1961-1980_2080-2099.nc \
  --orography-file /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/Emulator_hist_future/predictors/Static_fields.nc \
  --output-dir /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/Emulator_hist_future/predictors \
  --input-vars u v q t z \
  --input-levels 850 700 500 \
  --regrid-method bilinear

# ALPS_T2_CNRM-CM5_no_static
python compute_scalars_cordex.py \
  --predictor-files /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/Emulator_hist_future/predictors/CNRM-CM5_1961-1980_2080-2099.nc \
  --target-files /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/CORDEX/ALPS_domain/train/Emulator_hist_future/target/pr_tasmax_CNRM-CM5_1961-1980_2080-2099.nc \
  --no-static \
  --output-dir ./experiments/ALPS_T2_CNRM-CM5_no_static_scalars
