data:
  type: cordex
  training_predictor_paths:
    - ./granite-geospatial-wxc-downscaling/CORDEX/NZ_domain/train/ESD_pseudo_reality/predictors/ACCESS-CM2_1961-1980_regridded.nc
  training_target_paths:
    - ./granite-geospatial-wxc-downscaling/CORDEX/NZ_domain/train/ESD_pseudo_reality/target/pr_tasmax_ACCESS-CM2_1961-1980.nc
  validation_predictor_paths:
    - ./granite-geospatial-wxc-downscaling/CORDEX/NZ_domain/train/ESD_pseudo_reality/predictors/ACCESS-CM2_1961-1980_regridded.nc
  validation_target_paths:
    - ./granite-geospatial-wxc-downscaling/CORDEX/NZ_domain/train/ESD_pseudo_reality/target/pr_tasmax_ACCESS-CM2_1961-1980.nc
  test_predictor_paths:
    - ./granite-geospatial-wxc-downscaling/CORDEX/NZ_domain/train/ESD_pseudo_reality/predictors/ACCESS-CM2_1961-1980_regridded.nc
  test_target_paths:
    - ./granite-geospatial-wxc-downscaling/CORDEX/NZ_domain/train/ESD_pseudo_reality/target/pr_tasmax_ACCESS-CM2_1961-1980.nc
  static_path: ./granite-geospatial-wxc-downscaling/CORDEX/NZ_domain/train/ESD_pseudo_reality/predictors/Static_fields.nc
  input_vars: [u, v, q, t, z]
  input_levels: [850.0, 700.0, 500.0]
  input_surface_vars: []
  input_static_surface_vars: []
  vertical_pres_vars: [u, v, q, t, z]
  vertical_level1_vars: []
  vertical_level2_vars: []
  other: []
  output_vars: [pr, tasmax]
  input_level_pres: [850.0, 700.0, 500.0]
  input_level1: []
  input_level2: []
  n_input_timestamps: 1
  n_random_windows: 1
  input_size_lat: 16
  input_size_lon: 16
  target_size_lat: 256
  target_size_lon: 256
  crop_factor: 256
  downsample_factor: 8
  scalers:
    inputs_mean: /mnt/data2/kyo/granite-wxc/examples/CORDEX_ML/experiments/NZ_scalars/inputs_mean.npy
    inputs_std: /mnt/data2/kyo/granite-wxc/examples/CORDEX_ML/experiments/NZ_scalars/inputs_std.npy
    targets_mean: /mnt/data2/kyo/granite-wxc/examples/CORDEX_ML/experiments/NZ_scalars/targets_mean.npy
    targets_std: /mnt/data2/kyo/granite-wxc/examples/CORDEX_ML/experiments/NZ_scalars/targets_std.npy
predictands:
  pr:
    name: pr
    allow_negative_value: false
    nonnegativity:
      enabled: true
      method: softplus
    scaling:
      method: divide_only
      scale_stat: fixed
      fixed_scale: 100.0
  tasmax:
    name: tasmax
    allow_negative_value: false
    nonnegativity:
      enabled: false
      method: none
    scaling:
      method: zscore
      scale_stat: mean
      fixed_scale: null

model:
  input_mu: /mnt/data2/kyo/granite-wxc/examples/CORDEX_ML/experiments/NZ_scalars/inputs_mean.npy
  input_sigma: /mnt/data2/kyo/granite-wxc/examples/CORDEX_ML/experiments/NZ_scalars/inputs_std.npy
  target_mu: /mnt/data2/kyo/granite-wxc/examples/CORDEX_ML/experiments/NZ_scalars/targets_mean.npy
  target_sigma: /mnt/data2/kyo/granite-wxc/examples/CORDEX_ML/experiments/NZ_scalars/targets_std.npy
  embed_dim: 1024
  n_blocks_encoder: 8
  mlp_multiplier: 4
  n_heads: 16
  dropout_rate: 0.0
  drop_path: 0.0
  residual: none
  num_static_channels: 1
  downscaling_patch_size: [2, 2]
  downscaling_embed_dim: 512
  encoder_decoder_type: conv
  encoder_decoder_upsampling_mode: pixel_shuffle
  encoder_decoder_kernel_size_per_stage: [[3], [3]]
  encoder_decoder_scale_per_stage: [[2], [3]]
  encoder_decoder_conv_channels: 128
  residual_connection: true
  encoder_shift: false
  unet: true
job_id: cordex_nz_small
type_training: full_dataset
batch_size: 1
num_epochs: 5
dl_num_workers: 2
dl_prefetch_size: 1
learning_rate: 5.0e-05
limit_steps_train: 200
limit_steps_valid: 50
min_lr: 1.0e-06
max_lr: 1.0e-04
warm_up_steps: 0
mask_unit_size: [16, 16]
mask_ratio_inputs: 0.0
mask_ratio_targets: 0.0
max_batch_size: 4
path_experiment: ./examples/CORDEX_ML/experiments
path_model_weights: /mnt/data2/kyo/granite-wxc/granite-geospatial-wxc-downscaling/ECCC/weights/best_rmse_UNET_small.pt
backbone_use: true
backbone_freeze: false
backbone_prefix: encoder.
finetune_w_static: true
strict_matching: false
device_target: cuda
distributed_strategy: fsdp
fsdp_precision: bf16
fsdp_min_num_params: 5000000
backbone_gradient_checkpointing: true
skip_activation_offload: true
